[package]
name = "ctrl-lab"
version = "0.1.0"
description = "Embed Control Systems Easily."
edition = "2021"

[lib]
name = "ctrl_lab_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2.7.0"
tauri-plugin-fs = "2.5.0"
serde = { version = "1", features = ["derive"] }
ctrl-backend = { path = "../../backend" }
